### ISSUE TITLE
I am having problem with the modules

### ISSUE THREAD

**Issue by Vaibhav-Naik-26** [mipcit1010/Ticket-Bot#1]
I request you to please provide `package.json` and `package-lock.json` .

i am getting this error

```js
 node index.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/runner/Ticket-Bot/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/Ticket-Bot/node_modules/discord.js/src/index.js
- /home/runner/Ticket-Bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/Ticket-Bot/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/Ticket-Bot/node_modules/discord.js/src/client/BaseClient.js',
    '/home/runner/Ticket-Bot/node_modules/discord.js/src/index.js',
    '/home/runner/Ticket-Bot/index.js'
  ]
}
exit status 1
```

i fixed the above issue

and then when i run , it was showing some error with `chalk` so i downgraded it and then when i run , it is showing this error
please help, this i can't fix
```js
TypeError: Cannot read properties of undefined (reading 'SHARD_LIST')
    at Object.<anonymous> (/home/runner/Ticket-Bot/index.js:9:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

**Comment by master1ous** [comment]
For the 2nd issue, run cluster.js not index.js

**Comment by roshan1885** [comment]
For the first issue: Upgrade NodeJS Version.

**Comment by Vaibhav-Naik-26** [comment]
> For the 2nd issue, run cluster.js not index.js

i run cluster.js now and it shows error
```js
 node cluster.js
/home/runner/Ticket-Bot/node_modules/discord-hybrid-sharding/src/Structures/Queue.js:73
            timeout: item.timeout ?? this.options.timeout,
                                   ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/Ticket-Bot/node_modules/discord-hybrid-sharding/src/Core/ClusterManager.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
exit status 1
```

**Comment by master1ous** [comment]
Like said, install node 16+

**Comment by Vaibhav-Naik-26** [comment]
https://github.com/mipcit1010/Ticket-Bot/issues/1#issuecomment-1139319807

still error, mine is node 16.9

**Comment by Vaibhav-Naik-26** [comment]
I request the @mipcit1010 to add `package.json` file.

**Comment by Technology-King** [comment]
I request again, @mipcit1010  to add `package.json` file.

**Comment by master1ous** [comment]
> I request again, @mipcit1010 to add `package.json` file.

Hello, sorry for the inconvenience but this code is no longer supported,
There is a new repository for a Demo ticket bot using mongo db, which works.
I might upload a newer version of this current code sometime.

**Comment by Vaibhav-Naik-26** [comment]
Ok
